### ISSUE TITLE
setting RenderTarget for ThreeJS v102 

### ISSUE THREAD

**Issue by raphaelrauwolf** [Looking-Glass/HoloPlayJS_Issues#5]
Api in ThreeJS v102 changed to not setting the render target in the `renderer.render` function.

So `captureViews` and `HoloPlay.prototype.render` need updates.

`captureViews`
```
renderer.setRenderTarget(bufferSceneRender);
renderer.render(scene, arraycamera);
```

`HoloPlay.prototype.render`
```
renderer.setRenderTarget(null);
renderer.render(finalRenderScene, finalRenderCamera);
```

**Comment by alxdncn** [comment]
This has been fixed in our update, v0.2.0, coming next week.
